// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ3pLNDOVze9t_eRytK-LLiozdTO25noQ',
    appId: '1:320224193355:web:d1548d8c8d4f10c50396ce',
    messagingSenderId: '320224193355',
    projectId: 'kanramusic',
    authDomain: 'kanramusic.firebaseapp.com',
    storageBucket: 'kanramusic.firebasestorage.app',
    measurementId: 'G-2F361B01BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY1_P4q7488VHNSG6XAtphBaNsE-EunMU',
    appId: '1:320224193355:android:a6f6d0a350a0bdac0396ce',
    messagingSenderId: '320224193355',
    projectId: 'kanramusic',
    storageBucket: 'kanramusic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1qvygMqSKhn6w78edAk1tUQwBkSd9A8',
    appId: '1:320224193355:ios:c70cf1971106875c0396ce',
    messagingSenderId: '320224193355',
    projectId: 'kanramusic',
    storageBucket: 'kanramusic.firebasestorage.app',
    iosBundleId: 'com.example.kanraMusic',
  );
}
